// tests/goldSamples.js
// 넝쿨 골드샘플 리스트 (기대 모드 포함)
//
// MODES: DELAY / STABILIZE / REFLECT / SIMPLIFY / DECISIVE / EXPLORATORY

export const goldSamples = [


  { id: 1, text: 	"해야 할 일은 머릿속에 계속 맴도는데, 뭘 먼저 해야 할지 모르겠다. 그냥 넷플릭스나 보면서 내일로 미루고 싶다.", expected: 	"DELAY"	 },
  { id: 2, text: 	"오늘도 할 일을 적어보긴 했는데, 아무것도 손에 안 잡힌다. 생각만 많고 몸은 도무지 움직여지지 않는다.", expected: 	"DELAY"	 },
  { id: 3, text:	"회사 일도, 공부도, 정리도 다 중요해 보이는데 자꾸만 멍하니 시간만 흘려보내고 있다. 뭘 포기해야 할지도 모르겠다."	, expected: 	"DELAY"	 },
  { id: 4, text:	"해야 할 일은 많은데 몸이 너무 피곤해서 아무것도 손에 잡히지 않는다",	expected: 	"DELAY"	 },
  { id: 5, text:	"그냥 아무 생각 없이 침대에 누워 있고 싶다"	, expected: 	"DELAY"	 },
  { id: 6, text:	"오늘 하루는 집중도 안 되고 자꾸 딴생각만 난다."	, expected: 	"DELAY"	 },
  { id: 7, text:	"움직이기가 너무 귀찮다. 밥 먹는 것도 일이다."	, expected: 	"DELAY"	 },
  { id: 8, text:	"뭘 먼저 해야 할지 몰라서 멍하게 시간만 흘려보냈다."	, expected: 	"DELAY"	 },
  { id: 9, text:	"책상 앞에 앉았는데도 손이 안 움직여서 그냥 포기했다."	, expected: 	"DELAY"	 },
  { id: 10, text:	"몸도 마음도 지쳐서 아무 의욕이 없다."	, expected: 	"DELAY"	 },
  { id: 11, text:	"오늘은 아무 계획도 안 세우고 그냥 쉬고 싶다"	, expected: 	"DELAY"	 },
  { id: 12, text:	"머릿속이 너무 복잡해서 정리가 안 된다. 그냥 누워있고 싶다"	, expected: 	"DELAY"	 },
  { id: 13, text:	"일단 오늘은 버티는 게 전부다."	, expected: 	"REFLECT" },
  { id: 14, text:	"요즘 너무 달려온 것 같다. 이번 주말에는 새로운 걸 시작하기보다는 수면이랑 식단부터 좀 정리해서 컨디션을 회복하고 싶다."	, expected: 	"STABILIZE"	 },
  { id: 15, text:	"오늘은 큰 목표 말고, 밀려 있던 집안일이랑 장보기 정도만 천천히 처리하고 싶다. 일단 생활 리듬부터 다시 맞춰야겠다."	, expected: 	"STABILIZE"	 },
  { id: 16, text:	"일을 벌리면 금방 지쳐버려서, 당분간은 새로운 계획 없이 지금 하고 있는 것들만 안정적으로 유지하고 싶다"	, expected: 	"STABILIZE"	 },
  { id: 17, text:	"요 며칠 흐트러진 생활 리듬을 다시 잡고 싶다."	, expected: 	"STABILIZE"	 },
  { id: 18, text:	"새로운 일을 벌이기보다는 지금 하고 있는 걸 유지하는 데 집중해야겠다."	, expected: 	"STABILIZE"	 },
  { id: 19, text:	"가벼운 산책과 식단 조절부터 다시 시작해야 할 듯하다."	, expected: 	"STABILIZE"	 },
  { id: 20, text:	"당장은 큰 변화보다 안정적으로 하루를 보내고 싶다"	, expected: 	"STABILIZE"	 },
  { id: 21, text: "이번 주는 무리하지 않고 컨디션 유지에 집중해보려고 한다", expected: "STABILIZE" },
  { id: 22, text:	"잠을 규칙적으로 자는 것부터 회복해야겠다."	, expected: 	"STABILIZE"	 },
  { id: 23, text:	"지금은 욕심을 내기보다 기본 루틴을 다시 정비할 때다."	, expected: 	"STABILIZE"	 },
  { id: 24, text:	"최근 불안정했던 감정을 조금 가라앉히고 싶다."	, expected: 	"STABILIZE"	 },
  { id: 25, text:	"오늘은 평소 해오던 루틴을 유지하는 데 의미를 두려고 한다."	, expected: 	"STABILIZE"	 },
  { id: 26, text:	"일단 지금의 체력과 마음 상태를 안정시키는 게 먼저다."	, expected: 	"STABILIZE"	 },
  { id: 27, text:	"이번 주에 사람들한테 너무 예민하게 반응했던 것 같다. 왜 그렇게 방어적으로 굴었는지, 내 감정을 좀 차분히 들여다보고 싶다."	, expected: 	"REFLECT"	 },
  { id: 28, text:	"일을 많이 했다는 느낌은 드는데, 정작 내가 진짜 원하는 방향으로 가고 있는지 모르겠다. 지난 몇 달을 돌아보면서 기준을 다시 세워보고 싶다."	, expected: 	"REFLECT"	 },
  { id: 29, text:	"오늘 있었던 일들을 글로 정리해 보니, 내가 반복해서 같은 패턴으로 고민하고 있다는 게 보인다. 이 패턴이 나에게 어떤 의미인지 더 깊게 생각해보고 싶다."	, expected: 	"REFLECT"	 },
  { id: 30, text:	"요즘 내가 왜 이런 생각을 하는지 스스로 이해해보고 싶다."	, expected: 	"REFLECT"	 },
  { id: 31, text:	"오늘 있었던 일들을 곱씹어보니 새로운 깨달음이 있다."	, expected: 	"REFLECT"	 },
  { id: 32, text:	"내가 요즘 반복하는 행동 패턴을 다시 들여다보고 있다"	, expected: 	"REFLECT"	 },
  { id: 33, text:	"마음속에서 불편하게 걸리는 게 무엇인지 이유를 찾고 싶다."	, expected: 	"REFLECT"	 },
  { id: 34, text:	"감정이 왜 이렇게 흔들리는지 원인을 분석해보고 싶다."	, expected: 	"REFLECT"	 },
  { id: 35, text:	"최근 내 선택이 옳았는지 돌아보는 시간이 필요하다."	, expected: 	"REFLECT"	 },
  { id: 36, text:	"혼자 조용히 생각을 정리하는 시간이 갖고 싶었다."	, expected: 	"REFLECT"	 },
  { id: 37, text:	"내 감정이 너무 민감하게 반응한 이유를 알고 싶다."	, expected: 	"REFLECT"	 },
  { id: 38, text:	"지금의 고민을 더 깊이 들여다보면 방향이 보일 것 같다."	, expected: 	"REFLECT"	 },
  { id: 39, text:	"오늘은 내면 관찰에 시간이 더 많이 쓰였다."	, expected: 	"REFLECT"	 },
  { id: 40, text:	"해야 할 일 목록이 너무 길어서 보기만 해도 숨이 막힌다. 이번 주 안에 꼭 해야 하는 것 세 개만 남기고 나머지는 과감히 미루고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 41, text:	"사이드 프로젝트가 너무 많아졌다. 지금은 한두 개만 남기고, 나머지는 정리해서 에너지를 집중해야 할 것 같다."	, expected: 	"SIMPLIFY"	 },
  { id: 42, text:	"목표를 세분화해 놓다 보니 관리가 안 된다. 오늘은 To-Do를 최대 세 줄까지만 남기고, 그중 하나라도 끝내는 걸 목표로 삼고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 43, text:	"할 일을 세 줄로 압축해서 가장 중요한 것만 남기고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 44, text:	"오늘은 복잡한 생각을 내려놓고 필요한 것만 정리할 거다."	, expected: 	"SIMPLIFY"	 },
  { id: 45, text:	"해야 할 일 목록을 최소화해서 부담을 줄이고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 46, text:	"불필요한 일정들을 정리해서 핵심만 남기고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 47, text:	"지금 계획을 다시 단순하게 설계할 필요가 있다."	, expected: 	"SIMPLIFY"	 },
  { id: 48, text:	"오늘은 하고 싶은 것보다 반드시 해야 하는 것만 고르고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 49, text:	"책상 위와 마음속을 동시에 미니멀하게 정리하고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 50, text:	"내가 집중해야 할 목표를 딱 하나로 줄였다."	, expected: 	"SIMPLIFY"	 },
  { id: 51, text:	"오늘은 To-Do를 3개 이하로 유지하기로 했다."	, expected: 	"SIMPLIFY"	 },
  { id: 52, text:	"실행하기 위한 최소한의 조건만 남기고 나머지는 제거하고 싶다."	, expected: 	"SIMPLIFY"	 },
  { id: 53, text:	"지금 필 받았다. 이대로 끝까지 가면 돼."	, expected: 	"DECISIVE"	 },
  { id: 54, text: "망설일 이유가 없어. 답은 이미 나와 있잖아.", expected: "DECISIVE" },
  { id: 55, text: "오늘 안에 무조건 끝낼 수 있을 것 같은 자신감이 들어.", expected: "DECISIVE" },
  { id: 56, text: "오늘 안에 이 일을 꼭 끝내기로 마음먹었다.", expected: "DECISIVE" },
  { id: 57, text: "이번 주는 결과물을 반드시 만들어낸다.", expected: "DECISIVE" },
  { id: 58, text: "지금 바로 시작하면 충분히 해낼 수 있을 것 같다.", expected: "DECISIVE" },
  { id: 59, text: "더 생각할 시간 없이 오늘 바로 행동해야겠다.", expected: "DECISIVE" },
  { id: 60, text: "오랫동안 미뤄왔던 문제를 오늘 해결하기로 결심했다.", expected: "DECISIVE" },

  { id: 61, text: "이 문제에 대해 완전히 다른 관점으로 접근해볼래.", expected: "EXPLORATORY" },
  { id: 62, text: "창의력이 샘솟는 기분, 낙서라도 끄적여봐야지.", expected: "EXPLORATORY" },
  { id: 63, text: "남들이 안 하는 짓을 한번 해보고 싶다.", expected: "EXPLORATORY" },
  { id: 64, text: "호기심이 생겨서 새로운 방법을 여러 가지 찾아보고 있다.", expected: "EXPLORATORY" },
  { id: 65, text: "오늘은 평소에 안 해보던 방식으로 시도해보고 싶다", expected: "EXPLORATORY" },
  { id: 66, text: "아이디어가 계속 떠올라서 이것저것 실험해보고 싶다.", expected: "EXPLORATORY" },
  { id: 67, text: "지금은 실패해도 괜찮다는 마음으로 자유롭게 탐색하는 중이다.", expected: "EXPLORATORY" },
  { id: 68, text: "창의적인 영감이 떠올라서 새로운 걸 배우고 싶다.", expected: "EXPLORATORY" },
];
